set dotenv-load := true

export DEFAULT_APPLICATION:="peaq"

# default lists actions
default:
  @just -f {{ source_file() }} --list

# build docker image 
docker-build application="$DEFAULT_APPLICATION": 
  #!/usr/bin/env bash
  set -xeufo pipefail  
  docker build --progress=plain -f Dockerfile.{{ application }} -t {{ application }}:latest .

# get shell in docker container
docker-shell application="$DEFAULT_APPLICATION": (docker-build application)
  #!/usr/bin/env bash
  set -xeufo pipefail  
  mkdir -p ./in || true
  mkdir -p ./out || true
  docker run -it -v $(pwd)/in:/in -v $(pwd)/out:/out --entrypoint bash {{ application }}:latest

# run docker image
docker-run application="$DEFAULT_APPLICATION": (docker-build application)
  #!/usr/bin/env bash
  set -xeufo pipefail  
  docker run -it {{ application }}:latest


